services:
  go:
    build:
      context: ..
      dockerfile: docker/golang.Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - ../:/go/src

  db:
    build:
      context: ..
      dockerfile: docker/mysql.Dockerfile
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: golang-db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  test_db:
    build:
      context: ..
      dockerfile: docker/mysql.Dockerfile
    container_name: mysql_test_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_golang_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-test-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql-data:
  mysql-test-data: